### ISSUE TITLE
I get an error

### ISSUE THREAD

**Issue by maylad31** [xuxy09/Texformer#3]
Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to /root/.cache/torch/checkpoints/resnet50-19c8e357.pth
100% 97.8M/97.8M [00:00<00:00, 125MB/s]
Traceback (most recent call last):
  File "demo.py", line 162, in <module>
    demo.run_demo(args)
  File "/usr/local/lib/python3.7/dist-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "demo.py", line 122, in run_demo
    self.get_smpl(img_tensor)
  File "demo.py", line 44, in get_smpl
    pred_vertices, pred_cam_t, pred_rotmat, pred_betas = self.rsc_runner.get_3D_batch(img_tensor, scale, pre_process=True)
  File "/content/f7b7c7758a46da49f84bc68b47997d69/Texformer/RSC_net/ra_test.py", line 34, in get_3D_batch
    input_batch = self.pre_process_batch(input_batch)
  File "/content/f7b7c7758a46da49f84bc68b47997d69/Texformer/RSC_net/ra_test.py", line 30, in pre_process_batch
    return (batch - torch.tensor(self.IMG_NORM_MEAN).view(1, -1, 1, 1)) / torch.tensor(self.IMG_NORM_STD).view(1, -1, 1, 1)
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

**Comment by xuxy09** [comment]
can you print the shape of "batch"?

**Comment by maylad31** [comment]
I think it may be due to smplx version. Which version did you use?

**Comment by maylad31** [comment]
hi, can you please help me with textures? I tried a lot to make it work but couldn't.

**Comment by xuxy09** [comment]
> Thanks yes the shape was not correct. Thank you for helping. I managed to save obj file without texture using nr.save_obj. However I can't save with textures. That's the last thing i need. By the way your code is awesome. this works nr.save_obj("result1.obj",verts1,faces1,textures=None) but this nr.save_obj("result2.obj",verts1,faces1,textures=uv_map_t) doesn't.

This seems like an issue with the external module. I haven't used this function before. I would recommend checking the documentation of the original repo.

**Comment by silvercondor** [comment]
hi @maylad31 what was your input for vertices and faces when you try to save_obj?

also were you able to make it work with textures?
